### ISSUE TITLE
Lol, ich kann Titel ändern :O

### ISSUE THREAD

**Issue by Nougat-Police** [l3d00m/pietsmiet_xposter#1]
Zuallererst habe ich es nicht auf dich abgesehen und ich hatte ja wohl recht mit deiner Namensnennung. Das dann der direkt Bann erfolgt und die komplette Situation einseitig und unvollständig dargestellt wird, ja sogar behauptet wird, ich hätte gegen Regel #7 verstoßen, obwohl mein Posting wesentlich früher erschien, ist schon dreist. Wie du Kommentare entfernst, sieht man immer schön an der Differenz zwischen der Anzahl abgegebener Kommentare und den tatsächlich Vorhandenen.

Der Mikkel-Satz sollte eine locker-flockig formulierte Art und Weise sein, um den Leser auf ps.de zu locken. Hat ja sonst keinen Mehrwert, wenn man direkt ne 1:1 Kopie hat. Zudem hat mein Upload-Plan noch auf eine falsch nummerierte Folge und das Werbevideo hingewiesen, bevor dein Bot überhaupt was gecheckt hat.

**Comment by saibotk** [comment]
1. Das hier ist Github, klär das woanders.
2. Du brauchst hier gar nicht so bes­ser­wis­se­risch gegen den Bot zu argumentieren und zu sagen das dein Post (von dem ich keine Ahnung habe) besser war. 
3. Der Reddit ist moderiert und diejenigen haben das Sagen: Wenn es heißt das nur der Bot den Plan hochläd, dann ist das so Punkt und Ende.
4. Der Raum für konstruktive Kritik ist trotzdem gegeben.

**Comment by Nougat-Police** [comment]
Würde ich gerne, aber "Weiterhin ermöglicht das Subreddit vernünftige Diskussionen mit anderen Mitgliedern der Pietsmiet-Community" sind leider bloß leere Worte von l3d00m. Richtig wäre "Hast du mal ein Problem wirst du gemodmuted".

**Comment by saibotk** [comment]
Das ist immernoch Github nicht Reddit. Danke und Ciao.

**Comment by Nougat-Police** [comment]
@saibotk Klopf dir mal den Sand aus der Mumu.

**Comment by saibotk** [comment]
Lol ich bin der Trol, ich kann kommentieren
